### ISSUE TITLE
Error while loading libcrypto.so.1.0.0 library

### ISSUE THREAD

**Issue by cantaylancapraz** [epi2me-labs/tutorials#14]
Hi,

I'm using Epi2Me with version 1.0.6.
I'm following [Isoform_Tutorial](https://github.com/epi2me-labs/tutorials/blob/master/tutorials/Isoform_Tutorial.ipynb).

On **Mapping reads to the reference** part, I got following error:
```
* Skipping building minimap index
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x99ce39]

goroutine 1 [running]:
github.com/biogo/hts/bam.(*Reader).Header(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/biogo/hts/bam/reader.go:66
github.com/shenwei356/seqkit/seqkit/cmd.BamToolbox(0x7ffe6bf4fbd6, 0x13, 0xb46574, 0x1, 0xb46574, 0x1, 0x0, 0x2)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/bam_toolbox.go:187 +0x769
github.com/shenwei356/seqkit/seqkit/cmd.glob..func2(0x12d4460, 0xc00000d6a0, 0x0, 0x2)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/bam.go:573 +0x8b8
github.com/spf13/cobra.(*Command).execute(0x12d4460, 0xc00000d680, 0x2, 0x2, 0x12d4460, 0xc00000d680)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x12d7100, 0xc00000d540, 0xc000274420, 0xc00009c010)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:887
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:53 +0x31
main.main()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x20
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x7cbbc7]

goroutine 20 [running]:
github.com/biogo/hts/bam.(*Reader).Read(0x0, 0x0, 0x0, 0x0)
	/home/shenwei/shenwei/scripts/go/src/github.com/biogo/hts/bam/reader.go:118 +0x37
github.com/shenwei356/seqkit/seqkit/cmd.NewBamReaderChan.func1(0x0, 0xc00005d9e0)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/bam_toolbox.go:94 +0x6a
created by github.com/shenwei356/seqkit/seqkit/cmd.NewBamReaderChan
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/bam_toolbox.go:92 +0x20f
[WARNING] Indexing parameters (-k, -w or -H) overridden by parameters used in the prebuilt index.
[ERROR] failed to write the results
samtools: error while loading shared libraries: libcrypto.so.1.0.0: cannot open shared object file: No such file or directory
```
It looks libcrypto.so.1.0.0 is missing. Did you get this problem before? I can share any other information if needed?

The script I got this error: 
```
# **Alignment and filtering with `minimap2`** *(click to show)*
import yaml
min_mapping_quality = 40 

# Secondary filtering
poly_context = 24
max_poly_run = 8
context_plot_alignments = 5000

alignments_dir = os.path.join(analysis_folder, 'alignments')

# create minimap index
index_dir = os.path.join(analysis_folder, 'index')
!mkdir -p $index_dir
ref = input_dict['reference']
minimap_index = os.path.join(index_dir, "genome_index.mmi")
if rebuild_index or not os.path.exists(minimap_index):
    print("* Building minimap index...")
    !minimap2 -t $threads -k14 -I 1000G -d $minimap_index $ref \
    && echo "✓ Built index!"
else:
    print("* Skipping building minimap index")

!mkdir -p $alignments_dir
minimap_out_bam = os.path.join(alignments_dir, "reads_aln_sorted.bam")
unfiltered_sam = os.path.join(alignments_dir, "unfiltered.sam")

filtered_tsv = os.path.join(alignments_dir, "internal_priming_fail.tsv")
context_filt = {
    "AlnContext": {
        "Ref": ref,
        "LeftShift": -poly_context,
        "RightShift": poly_context,
        "RegexEnd": "[Aa]{{{pr},}}".format(pr=max_poly_run),
        "Stranded": True,
        "Invert": True,
        "Tsv": filtered_tsv}}
with open('filt.yaml', 'w') as outfile:
    yaml.dump(context_filt, outfile)

!rm -rf $minimap_out_bam
!minimap2 -t $threads -ax splice -uf $minimap_index $full_length_reads \
    | samtools view -q $min_mapping_quality -F2304 -bS - \
    | seqkit_bam_yaml filt.yaml \
    | samtools sort -@ $threads -o $minimap_out_bam -
!samtools index $minimap_out_bam
```

Thanks

**Comment by cjw85** [comment]
Hi @cantaylancapraz,

Thank you for your patience. We are looking into this issue and will have an update shortly.

**Comment by cantaylancapraz** [comment]
@cjw85 Do you have any recommendation to solve problem as workaround?

**Comment by cjw85** [comment]
We've not been able to reproduce this. We will have a new release of the notebook server this afternoon (hopefully). I will try again to reproduce the issue

**Comment by cantaylancapraz** [comment]
Okey. I would provide more information if you need.

**Comment by cantaylancapraz** [comment]
Hi, any update on this issue?

**Comment by sagrudd** [comment]
@cantaylancapraz - have you tried the new version of EPI2ME Labs? The LabsLauncher was updated a couple of weeks ago and the docker containers used have also been updated. The `libcrypto` messages that I have seen in the past have been due to mischief during the conda package installation - would be useful to know if you are still seeing this error (from the new container environment)

**Comment by cantaylancapraz** [comment]
Hi, 

I was trying with version 1.0.7, and it didn't work in this version. I upgraded it to 1.0.9, and I can complete the tutorial without any problems in version 1.0.9.

Thanks for support
